src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <summarizedField>Contratto__c.ChiamateAnnuali__c</summarizedField>
        <summaryForeignKey>Contratto__c.Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ChiamateEffettuateSandbox__c</fullName>
        <label>Chiamate Effettuate Sandbox</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChiamateMensiliRimanenti__c</fullName>
        <formula>LimiteChiamateMensiliTotali__c +  DeltaChiamateMensili__c - ChiamateMensili__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chiamate Mensili Rimanenti</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <summarizedField>Contratto__c.ChiamateMensili__c</summarizedField>
        <summaryForeignKey>Contratto__c.Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ChiamateRimanentiSandbox__c</fullName>
        <formula>LimiteChiamateSandbox__c - ChiamateEffettuateSandbox__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chiamate Rimanenti Sandbox</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChiamateTotali__c</fullName>
        <label>Chiamate Totali</label>
        <summarizedField>Contratto__c.ChiamateTotali__c</summarizedField>
        <summaryForeignKey>Contratto__c.Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>DeltaChiamateMensili__c</fullName>
        <label>Delta Chiamate Mensili</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IdOrgCliente__c</fullName>
        <label>Id Org Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LimiteChiamateMensiliTotali__c</fullName>
        <label>Limite Chiamate Mensili Totali</label>
        <summarizedField>Contratto__c.LimiteChiamateMensiliTotali__c</summarizedField>
        <summaryForeignKey>Contratto__c.Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LimiteChiamateSandbox__c</fullName>
        <label>Limite Chiamate Sandbox</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contratto__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Contratti</relationshipLabel>
        <relationshipName>Contratto</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <summarizedField>Licenza__c.ChiamateAnnuali__c</summarizedField>
        <summaryForeignKey>Licenza__c.Contratto__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <summarizedField>Licenza__c.ChiamateMensili__c</summarizedField>
        <summaryForeignKey>Licenza__c.Contratto__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ChiamateTotali__c</fullName>
        <label>Chiamate Totali</label>
        <summarizedField>Licenza__c.ChiamateTotali__c</summarizedField>
        <summaryForeignKey>Licenza__c.Contratto__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LimiteChiamateMensiliTotali__c</fullName>
        <formula>NumeroLicenze__c * LimiteChiamateMensiliUtente__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Limite Chiamate Mensili Totali</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contratto</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Numero Contratto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratti</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Licenza__c.object
<CustomObject>
    <fields>
        <fullName>AttivaCheckbox__c</fullName>
        <formula>AND( Contratto__r.AttivoCheckbox__c , NOT( Disattiva__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attiva Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChiamateTotali__c</fullName>
        <label>Chiamate Totali</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contratto__c</fullName>
        <label>Contratto</label>
        <referenceTo>Contratto__c</referenceTo>
        <relationshipLabel>Licenze</relationshipLabel>
        <relationshipName>Licenza</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IdUtenteCliente__c</fullName>
        <externalId>true</externalId>
        <label>Id Utente Cliente</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Licenza</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Numero Licenza</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenze</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/API_INBOUND_LicenseIncrement.cls
@RestResource(urlMapping='/license/increment')
global class API_INBOUND_LicenseIncrement {

    @HttpPost
    global static IncrementLicenseWrapperResponse execute(String orgId, String secretKey, String environment, String userId) {
        IncrementLicenseWrapperResponse res = new IncrementLicenseWrapperResponse();
        if(String.isBlank(orgId) || String.isBlank(secretKey) || String.isBlank(environment) || String.isBlank(userId)){
            res.setError('E002');
        }
        else{
            List<Asset> assets = [SELECT Id,IdOrgCliente__c,LimiteChiamateMensiliTotali__c,DeltaChiamateMensili__c,ChiamateMensili__c,ChiamateMensiliRimanenti__c,LimiteChiamateSandbox__c,ChiamateEffettuateSandbox__c,ChiamateRimanentiSandbox__c FROM Asset WHERE SerialNumber = :secretKey];
            if(assets != null && !assets.isEmpty() && ( environment == 'SANDBOX' || assets[0].IdOrgCliente__c == orgId )){
                if(environment == 'PRODUCTION'){
                    List<Licenza__c> lis = [SELECT  Id,
                                                    IdUtenteCliente__c, 
                                                    AttivaCheckbox__c,
                                                    ChiamateMensili__c,
                                                    ChiamateAnnuali__c,
                                                    ChiamateTotali__c,
                                                    Contratto__r.Asset__r.ChiamateMensiliRimanenti__c
                                                FROM Licenza__c 
                                                WHERE Contratto__r.Asset__c = :assets[0].Id AND IdUtenteCliente__c = :userId
                    ];
                    if(lis != null && !lis.isEmpty()){
                        if(lis[0].AttivaCheckbox__c){
                            if(lis[0].Contratto__r.Asset__r.ChiamateMensiliRimanenti__c > 0){
                                lis[0].ChiamateMensili__c = lis[0].ChiamateMensili__c == null ? 1 : lis[0].ChiamateMensili__c + 1;
                                lis[0].ChiamateAnnuali__c = lis[0].ChiamateAnnuali__c == null ? 1 : lis[0].ChiamateAnnuali__c + 1;
                                lis[0].ChiamateTotali__c = lis[0].ChiamateTotali__c == null ? 1 : lis[0].ChiamateTotali__c + 1;
                                Database.SaveResult sr = Database.update(lis[0]);
                                if(!sr.success || (Test.isRunningTest() && lis[0].IdUtenteCliente__c == 'USER_0002')){
                                    res.setError('E010',Test.isRunningTest() ? 'Apex error' : ''+sr.getErrors()[0].getMessage());
                                }
                            }
                            else{
                                res.setError('E007');
                            }
                        }
                        else{
                            res.setError('E006');
                        }
                    }
                    else{
                        res.setError('E005');
                    }
                }
                else{
                    if(assets[0].ChiamateRimanentiSandbox__c > 0){
                        assets[0].ChiamateEffettuateSandbox__c = assets[0].ChiamateEffettuateSandbox__c == null ? 1 : assets[0].ChiamateEffettuateSandbox__c + 1;
                        Database.SaveResult sr = Database.update(assets[0]);
                        if(!sr.success || (Test.isRunningTest() && userId == 'USER_0002')){
                            res.setError('E010',Test.isRunningTest() ? 'Apex error' : ''+sr.getErrors()[0].getMessage());
                        }
                    }
                    else{
                        res.setError('E007');
                    }
                }
            }
            else{
                res.setError('E004');
            }
        }
        return res;
    }

    global class IncrementLicenseWrapperResponse {
        global Boolean success {get;set;}
        global API_INBOUND_Utils.ErrorWrapper error { get;set; }

        public IncrementLicenseWrapperResponse(){
            this.success = true;
        }

        public void setError(String errorCode){
            this.success = false;
            this.error = new API_INBOUND_Utils.ErrorWrapper(errorCode);
        }

        public void setError(String errorCode, String errorMessage){
            this.success = false;
            this.error = new API_INBOUND_Utils.ErrorWrapper(errorCode,errorMessage);
        }
    }
}