src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <summarizedField>Contratto__c.ChiamateAnnuali__c</summarizedField>
        <summaryForeignKey>Contratto__c.Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <summarizedField>Contratto__c.ChiamateMensili__c</summarizedField>
        <summaryForeignKey>Contratto__c.Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>IdOrgCliente__c</fullName>
        <label>Id Org Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LimiteChiamateSandbox__c</fullName>
        <label>Limite Chiamate Sandbox</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contratto__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contratto</relationshipLabel>
        <relationshipName>Contratti</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Contratti</relationshipLabel>
        <relationshipName>Contratto</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <summarizedField>Licenza__c.ChiamateAnnuali__c</summarizedField>
        <summaryForeignKey>Licenza__c.Contratto__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <summarizedField>Licenza__c.ChiamateMensili__c</summarizedField>
        <summaryForeignKey>Licenza__c.Contratto__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>DataFine__c</fullName>
        <label>Data Fine</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DataInizio__c</fullName>
        <label>Data Inizio</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ResetContatoreAnnuale__c</fullName>
        <label>Reset Contatore Annuale</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ResetContatoreMensile__c</fullName>
        <label>Reset Contatore Mensile</label>
        <type>Date</type>
    </fields>
    <label>Contratto</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Numero Contratto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratti</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Licenza__c.object
<CustomObject>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contratto__c</fullName>
        <label>Contratto</label>
        <referenceTo>Contratto__c</referenceTo>
        <relationshipLabel>Licenze</relationshipLabel>
        <relationshipName>Licenza</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IdUtenteCliente__c</fullName>
        <externalId>true</externalId>
        <label>Id Utente Cliente</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Licenza</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Numero Licenza</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenze</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResetContatoriTest.cls
@isTest
private with sharing class ResetContatoriTest {
    @TestSetup
    static void makeData(){
        Product2 pro0 = new Product2(
            Name = 'Test Product 0',
            ProductCode = 'P_0001'
        );
        insert pro0;

        Account acc0 = new Account(
                Name = 'Test Account 0'
        );
        insert acc0;

        Asset ass0 = new Asset(
            Name = 'Test Asset 0',
            AccountId = acc0.Id,
            Product2Id = pro0.Id,
            SerialNumber = 'S_0001',
            IdOrgCliente__c = 'ORG_01',
            LimiteChiamateSandbox__c = 10
        );
        insert ass0;

        ContrattoTriggerHandler.manualSkip = true;
        Contratto__c con0 = new Contratto__c(
            Asset__c = ass0.Id,
            Account__c = acc0.Id,
            DataInizio__c = System.today().addYears(-1),
            DataFine__c = System.today().addYears(1),
            ResetContatoreMensile__c = System.today(),
            ResetContatoreAnnuale__c = System.today()
        );
        insert con0;

        List<Licenza__c> lics = new List<Licenza__c>();
        lics.add(new Licenza__c(
            Contratto__c = con0.Id,
            IdUtenteCliente__c = 'USER_0001',
            ChiamateMensili__c = 10,
            ChiamateAnnuali__c = 50
        ));
        lics.add(new Licenza__c(
            Contratto__c = con0.Id,
            IdUtenteCliente__c = 'USER_0002',
            ChiamateMensili__c = 0,
            ChiamateAnnuali__c = 0
        ));
        insert lics;
        ContrattoTriggerHandler.manualSkip = false;
    }

    @IsTest
    static void resetContatoriTest(){

        Test.startTest();

        ResetContatoriSched rcs = new ResetContatoriSched();
        rcs.execute(null);

        Test.stopTest();

        List<Licenza__c> licenses = [SELECT Id,ChiamateMensili__c,ChiamateAnnuali__c FROM Licenza__c ORDER BY IdUtenteCliente__c];
        System.assertEquals(0,licenses[0].ChiamateMensili__c);
        System.assertEquals(0,licenses[0].ChiamateAnnuali__c);
        System.assertEquals(0,licenses[1].ChiamateMensili__c);
        System.assertEquals(0,licenses[1].ChiamateAnnuali__c);

        Contratto__c c = [SELECT Id,ResetContatoreMensile__c,ResetContatoreAnnuale__c FROM Contratto__c LIMIT 1];
        System.assertEquals(System.today().addMonths(1),c.ResetContatoreMensile__c);
        System.assertEquals(System.today().addYears(1),c.ResetContatoreAnnuale__c);
    }
}