src/objects/Contratto__c.object
<CustomObject>
    <fields>
        <fullName>AttivoCheckbox__c</fullName>
        <formula>AND(NOT(Disattiva__c),TODAY() &gt;=  DataInizio__c , TODAY() &lt;=  DataFine__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attivo Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <summarizedField>Licenza__c.ChiamateAnnuali__c</summarizedField>
        <summaryForeignKey>Licenza__c.Contratto__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <summarizedField>Licenza__c.ChiamateMensili__c</summarizedField>
        <summaryForeignKey>Licenza__c.Contratto__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ResetContatoreAnnuale__c</fullName>
        <label>Reset Contatore Annuale</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ResetContatoreMensile__c</fullName>
        <label>Reset Contatore Mensile</label>
        <type>Date</type>
    </fields>
    <label>Contratto</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Numero Contratto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratti</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Licenza__c.object
<CustomObject>
    <fields>
        <fullName>ChiamateAnnuali__c</fullName>
        <label>Chiamate Annuali</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChiamateMensili__c</fullName>
        <label>Chiamate Mensili</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contratto__c</fullName>
        <label>Contratto</label>
        <referenceTo>Contratto__c</referenceTo>
        <relationshipLabel>Licenze</relationshipLabel>
        <relationshipName>Licenza</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licenza</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Numero Licenza</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenze</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResetContatoriBatch.cls
public with sharing class ResetContatoriBatch implements Database.Batchable<sObject>{

    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id,Contratto__c,Contratto__r.ResetContatoreMensile__c,Contratto__r.ResetContatoreAnnuale__c FROM Licenza__c WHERE (Contratto__r.ResetContatoreMensile__c = TODAY OR Contratto__r.ResetContatoreAnnuale__c = TODAY) AND Contratto__r.AttivoCheckbox__c = true';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Licenza__c> scope){
        Map<String,Contratto__c> contractsByIdMap = new Map<String,Contratto__c>();
        for(Licenza__c l : scope){
            if(contractsByIdMap.get(l.Contratto__c) == null) 
                contractsByIdMap.put(l.Contratto__c,new Contratto__c(Id = l.Contratto__c));
            if(l.Contratto__r.ResetContatoreMensile__c == System.today()){
                l.ChiamateMensili__c = 0;
                contractsByIdMap.get(l.Contratto__c).ResetContatoreMensile__c = System.today().addMonths(1);
            }
            if(l.Contratto__r.ResetContatoreAnnuale__c == System.today()){
                l.ChiamateAnnuali__c = 0;
                contractsByIdMap.get(l.Contratto__c).ResetContatoreAnnuale__c = System.today().addYears(1);
            }
        }
        ContrattoTriggerHandler.manualSkip = true;
        update scope;
        update contractsByIdMap.values();
        ContrattoTriggerHandler.manualSkip = false;
    }
    
    public void finish(Database.BatchableContext bc){}
}